site_name: "M2 IIN Mediatheque project Documentation"
theme:
  name: "material"
docs_dir: "./docs"
nav:
  - Home: index.md
  - Development: 
    - prerequisites: dev/pre.md
    - initialisation: dev/init.md
    - useful: dev/usefull.md
  - Datamodel: model.md
  - Architedture: archidev.md
  - About: about.md